@startuml
left to right direction

actor owner as "owner (a legal entity)"


rectangle "Manage owners" {

	(Register owner)
	(Deregister owner)
	(Block owner)
	(Unblock owner)
	(Reset owner\ncredentials)

}

rectangle "Manage entities" {
	(Register entity)
	(Deregister entity)
	(Block entity)
	(Unblock entity)
	(Reset entity\ncredentials)

}

rectangle "Access control" {

	(Send a follow\nrequest)
	(Approve a follow\nrequest)
	(Unfollow)
	(Get list of\nfollow requests)
	(Reject a\nfollow request)
	(Get follow status)
}

rectangle "Data access" {

	(Publish)
	(Subscribe)

	(Bind to\na data stream)
	(Unbind from\n a data stream)
	(Get a list of\naccessible\ndata streams)
}

rectangle "Search" {
	(Search catalog)
}


(Unblock owner) <-- admin
(Block owner) <-- admin
(Deregister owner) <-- admin
(Register owner) <-- admin
(Reset owner\ncredentials) <-- admin


admin --> (Unblock entity)
admin --> (Block entity)

(Reset entity\ncredentials) <-- owner
(Register entity) <-- owner
(Deregister entity) <-- owner
(Unblock entity) <-- owner
(Block entity) <-- owner


owner --> (Approve a follow\nrequest)
owner --> (Send a follow\nrequest)
owner --> (Unfollow)


(Bind to\na data stream) <-- owner
(Unbind from\n a data stream) <-- owner
(Get a list of\naccessible\ndata streams) <-- owner

owner --> (Get list of\nfollow requests)
owner --> (Reject a\nfollow request)
owner --> (Get follow status)

owner --> (Search catalog)

entity entity

(Publish) <-- entity
(Subscribe) <-- entity
(Get a list of\naccessible\ndata streams) <-- entity
(Search catalog) <-- entity

entity "autonomous entity" as a
entity <|- a : is an

(Send a follow\nrequest) <-- a
(Approve a follow\nrequest) <-- a
(Reject a\nfollow request) <-- a
(Get follow status) <-- a
(Unfollow) <-- a
(Get list of\nfollow requests) <-- a

@enduml
