#!/bin/bash

curl -i -k -XPOST \
	'https://localhost:8443/auth/v1/acl/set' \
	-H 'content-type: application/json' \
	-d '{
		"policy": "consumer@iisc.ac.in can access example.com/test-category/test-resource-1 for 1 month;consumer@iisc.ac.in can access example.com/test-category/test-resource-2 for 1 month;consumer@iisc.ac.in can access example.com/test-category/test-resource-3 for 1 month;consumer@iisc.ac.in can access example.com/test-category/test-resource.public for 1 month"
	    }'    \
	--cert provider.pem    \
	--key provider.key.pem
