version: 2
updates:
- package-ecosystem: maven
  directory: "/api-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - pct960
  ignore:
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-client
    versions:
    - 7.12.0
- package-ecosystem: maven
  directory: "/authenticator"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - pct960
