#!/bin/bash

set -e
YELLOW='\033[1;33m'
NC='\033[0m'

if [ "$(uname)" == "Darwin" ]; then
	generate_key="head /dev/urandom | shasum | cut -f1 -d' '"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
	generate_key="head /dev/urandom | sha1sum | cut -f1 -d' '"
fi

admin_passwd="$(eval $generate_key)"
postgres_passwd="$(eval $generate_key)"
mongo_passwd="$(eval $generate_key)"


if [ -e ".env" ]
then
    rm .env
fi

echo "ADMIN_PWD="$admin_passwd > .env
echo "POSTGRES_PWD="$postgres_passwd >> .env
echo "SINGLE_NODE=true" >> .env
echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
echo "MONGO_INITDB_ROOT_PASSWORD="$mongo_passwd >> .env

docker-compose down -v
docker-compose up -d

echo -e "\n${YELLOW}Since this is a regular installation, please wait for 3-5 mins before using the middleware${NC}"
