#!/bin/bash

set -e
YELLOW='\033[1;33m'
NC='\033[0m'

admin_passwd="$(env LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 32 ; echo)"
postgres_passwd="$(env LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 32 ; echo)"
mongo_passwd="$(env LC_ALL=C tr -dc a-zA-Z0-9 < /dev/urandom | head -c 32 ; echo)"

if [ -e ".env" ]
then
    rm .env
fi

echo "ADMIN_PWD="$admin_passwd > .env
echo "POSTGRES_PWD="$postgres_passwd >> .env
echo "SINGLE_NODE=true" >> .env
echo "MONGO_INITDB_ROOT_USERNAME=root" >> .env
echo "MONGO_INITDB_ROOT_PASSWORD="$mongo_passwd >> .env

docker-compose down -v
docker-compose up -d

echo -e "\n${YELLOW}Since this is a regular installation, please wait for 3-5 mins before using the middleware${NC}"
