#!/bin/bash

directory=`dirname $0`
cd $directory

admin_passwd=`cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo`
postgres_passwd=`cat /dev/urandom | env LC_CTYPE=C tr -dc a-zA-Z0-9 | head -c 32; echo`

if [ -e ".env" ]
then
    rm .env
fi

echo "ADMIN_PWD="$admin_passwd > .env
echo "POSTGRES_PWD="$postgres_passwd >> .env
echo "QUICK_INSTALL=true" >> .env
echo "SINGLE_NODE=true" >> .env

docker-compose down -v
docker-compose up -d
