#!/bin/bash

#Install required packages on controller
set -ex
sudo apt update && sudo apt -y upgrade
sudo apt install -y python3 python3-pip python3-setuptools build-essential
sudo apt install -y docker.io
sudo pip3 install ansible docker-compose

hosts=$1

if [ $1 == "--rekey=true" ]
then
    ssh-keygen -t rsa
    hosts=$2
fi

for host in $(echo $hosts | sed "s/,/ /g")
do
    ssh-copy-id root@$host
done
