#!/bin/sh

id=`id | cut -f1 -d'('`
if [ $id != "uid=0" ]
then
	echo
	echo "You must be root to run this script"
	echo
	exit
fi

pkg_add git

cd /home
git clone --depth=1 https://github.com/datasetu/datasetu-auth-server

cd datasetu-auth-server
./setup
