
actor "owner" as owner
hide footbox

group HTTPS GET /owner/follow-status
owner -> IUDX: **id**: string\r**apikey**: string
end

group 200 OK
IUDX -> owner: [\l\t{\t\r\t\t"**follow-id**": string,\r\t\t"**from**": string,\r\t\t"**to**": string,\r\t\t"**time**": string,\r\t\t"**permission**": string,\r\t\t"**topic**": string,\r\t\t"**validity**": string,\r\t\t"**status**": string\r\t},\l\t ...\l]
end

