hide footbox
actor "owner of subscriber" as sowner


group HTTPS POST /owner/follow                                                  
    sowner -> IUDX: **id**: string\r**apikey**: string\r**to**: string\r**topic**: string\r**permission**: string\r**validity**: string
end                                                                              
                                                                                 
group 202 ACCEPTED                                                               
    IUDX -> sowner : {"**follow-id-read**": string, "**follow-id-write**": string}
end                                                                              
