actor admin
hide footbox

hnote over admin : logged on IUDX 
...

group HTTPS POST /admin/register-owner
admin -> IUDX: **id**: string\r**apikey**: string\r**owner**: string
end

create actor owner
IUDX -> owner : new account

group 201 CREATED
IUDX -> admin: {"**id**": string, "**apikey**": string}
end

@enduml
